# Generated by Django 5.2.7 on 2025-10-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_quantity_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.IntegerField()),
                ('input_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('ADD', 'Added'), ('DEDUCT', 'Deducted')], max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
    ]
