# Generated by Django 5.2.7 on 2025-10-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
