# Generated by Django 5.2.7 on 2025-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_userprofile_is_declined'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the inventory close.', unique=True)),
                ('snapshot_data', models.JSONField(help_text='JSON mapping category name to total units in stock.')),
            ],
            options={
                'verbose_name': 'Daily Inventory Snapshot',
                'verbose_name_plural': 'Daily Inventory Snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
