# Generated by Django 5.2.7 on 2025-10-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_dailyinventorysnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyInventorySnapshot',
        ),
    ]
