# Generated by Django 5.2.7 on 2025-10-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_producthistory_delete_productactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
    ]
