# Generated by Django 4.1.13 on 2025-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_producthistory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
